// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: laneq.proto

package laneqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority represents the priority level of a directive.
// Lower values indicate higher priority (P0 before P1 before P2).
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_P0          Priority = 1 // High priority
	Priority_PRIORITY_P1          Priority = 2 // Normal priority
	Priority_PRIORITY_P2          Priority = 3 // Low priority
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_P0",
		2: "PRIORITY_P1",
		3: "PRIORITY_P2",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_P0":          1,
		"PRIORITY_P1":          2,
		"PRIORITY_P2":          3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_laneq_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_laneq_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{0}
}

// Status represents the current state of a directive in the queue.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1 // Waiting to be claimed
	Status_STATUS_TAKEN       Status = 2 // Claimed by a consumer; has active lease
	Status_STATUS_DEFERRED    Status = 3 // Deferred until not_before; eligible for auto-promotion
	Status_STATUS_DONE        Status = 4 // Completed; removed from queue
	Status_STATUS_DROPPED     Status = 5 // Abandoned; removed from queue
	Status_STATUS_PARKED      Status = 6 // Durable hold; excluded from claim/peek/reap; never auto-promotes
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_TAKEN",
		3: "STATUS_DEFERRED",
		4: "STATUS_DONE",
		5: "STATUS_DROPPED",
		6: "STATUS_PARKED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_TAKEN":       2,
		"STATUS_DEFERRED":    3,
		"STATUS_DONE":        4,
		"STATUS_DROPPED":     5,
		"STATUS_PARKED":      6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_laneq_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_laneq_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{1}
}

// Directive is the unit of work in the queue.
// The body is opaque JSON; the proto models scheduling columns explicitly.
type Directive struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority       Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=laneq.v1.Priority" json:"priority,omitempty"`
	Body           string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"` // Opaque JSON (intent, template, origin, repo, ref, task, grade, deadline, etc.)
	Status         Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"`
	Lane           string                 `protobuf:"bytes,5,opt,name=lane,proto3" json:"lane,omitempty"`                                               // Queue lane (default: "default")
	CreatedAtUnix  int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`     // Unix timestamp
	TakenAtUnix    int64                  `protobuf:"varint,7,opt,name=taken_at_unix,json=takenAtUnix,proto3" json:"taken_at_unix,omitempty"`           // Unix timestamp; 0 if not yet taken
	DoneAtUnix     int64                  `protobuf:"varint,8,opt,name=done_at_unix,json=doneAtUnix,proto3" json:"done_at_unix,omitempty"`              // Unix timestamp; 0 if not yet done
	TakenBy        string                 `protobuf:"bytes,9,opt,name=taken_by,json=takenBy,proto3" json:"taken_by,omitempty"`                          // Consumer ID that claimed this directive
	LeaseUntilUnix int64                  `protobuf:"varint,10,opt,name=lease_until_unix,json=leaseUntilUnix,proto3" json:"lease_until_unix,omitempty"` // Unix timestamp; 0 if no active lease
	RequeueCount   int32                  `protobuf:"varint,11,opt,name=requeue_count,json=requeueCount,proto3" json:"requeue_count,omitempty"`         // Number of times requeued
	ParentId       string                 `protobuf:"bytes,12,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                      // Parent directive ID for threading; "" if root
	NotBeforeUnix  int64                  `protobuf:"varint,13,opt,name=not_before_unix,json=notBeforeUnix,proto3" json:"not_before_unix,omitempty"`    // Eligibility gate; 0 if always eligible
	BlockedBy      []string               `protobuf:"bytes,14,rep,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`                   // List of blocking directive IDs (dependencies)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Directive) Reset() {
	*x = Directive{}
	mi := &file_laneq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directive) ProtoMessage() {}

func (x *Directive) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directive.ProtoReflect.Descriptor instead.
func (*Directive) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{0}
}

func (x *Directive) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Directive) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Directive) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Directive) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Directive) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *Directive) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Directive) GetTakenAtUnix() int64 {
	if x != nil {
		return x.TakenAtUnix
	}
	return 0
}

func (x *Directive) GetDoneAtUnix() int64 {
	if x != nil {
		return x.DoneAtUnix
	}
	return 0
}

func (x *Directive) GetTakenBy() string {
	if x != nil {
		return x.TakenBy
	}
	return ""
}

func (x *Directive) GetLeaseUntilUnix() int64 {
	if x != nil {
		return x.LeaseUntilUnix
	}
	return 0
}

func (x *Directive) GetRequeueCount() int32 {
	if x != nil {
		return x.RequeueCount
	}
	return 0
}

func (x *Directive) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Directive) GetNotBeforeUnix() int64 {
	if x != nil {
		return x.NotBeforeUnix
	}
	return 0
}

func (x *Directive) GetBlockedBy() []string {
	if x != nil {
		return x.BlockedBy
	}
	return nil
}

// Push request enqueues a new directive.
type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`                                 // Opaque JSON
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=laneq.v1.Priority" json:"priority,omitempty"` // Default: PRIORITY_P1
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`         // Optional parent for threading
	Lane          string                 `protobuf:"bytes,4,opt,name=lane,proto3" json:"lane,omitempty"`                                 // Default: "default"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_laneq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{1}
}

func (x *PushRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PushRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *PushRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *PushRequest) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

// Push response returns the assigned ID and status.
type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=laneq.v1.Priority" json:"priority,omitempty"`
	Lane          string                 `protobuf:"bytes,3,opt,name=lane,proto3" json:"lane,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"` // Human-readable summary (e.g., "enqueued in lane 'default'")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_laneq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{2}
}

func (x *PushResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PushResponse) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *PushResponse) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *PushResponse) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *PushResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *PushResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// Take request claims the next eligible directive.
type TakeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Consumer         string                 `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`                                            // Consumer identifier
	Lane             string                 `protobuf:"bytes,2,opt,name=lane,proto3" json:"lane,omitempty"`                                                    // Default: "default"
	LeaseDurationMs  int64                  `protobuf:"varint,3,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"`    // Lease duration in milliseconds
	ReapStaleSeconds int64                  `protobuf:"varint,4,opt,name=reap_stale_seconds,json=reapStaleSeconds,proto3" json:"reap_stale_seconds,omitempty"` // Optional: reap leases older than this many seconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TakeRequest) Reset() {
	*x = TakeRequest{}
	mi := &file_laneq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeRequest) ProtoMessage() {}

func (x *TakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeRequest.ProtoReflect.Descriptor instead.
func (*TakeRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{3}
}

func (x *TakeRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *TakeRequest) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *TakeRequest) GetLeaseDurationMs() int64 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

func (x *TakeRequest) GetReapStaleSeconds() int64 {
	if x != nil {
		return x.ReapStaleSeconds
	}
	return 0
}

// Take response returns the claimed directive and lease.
type TakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directive     *Directive             `protobuf:"bytes,1,opt,name=directive,proto3" json:"directive,omitempty"` // The claimed directive; omitted (zero) if none available
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`   // Echo of the requesting consumer
	Lane          string                 `protobuf:"bytes,3,opt,name=lane,proto3" json:"lane,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeResponse) Reset() {
	*x = TakeResponse{}
	mi := &file_laneq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeResponse) ProtoMessage() {}

func (x *TakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeResponse.ProtoReflect.Descriptor instead.
func (*TakeResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{4}
}

func (x *TakeResponse) GetDirective() *Directive {
	if x != nil {
		return x.Directive
	}
	return nil
}

func (x *TakeResponse) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *TakeResponse) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

// Peek request queries the next eligible directive without claiming.
type PeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lane          string                 `protobuf:"bytes,1,opt,name=lane,proto3" json:"lane,omitempty"` // Default: "default"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekRequest) Reset() {
	*x = PeekRequest{}
	mi := &file_laneq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekRequest) ProtoMessage() {}

func (x *PeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekRequest.ProtoReflect.Descriptor instead.
func (*PeekRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{5}
}

func (x *PeekRequest) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

// Peek response returns the directive (if any) without claiming.
type PeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directive     *Directive             `protobuf:"bytes,1,opt,name=directive,proto3" json:"directive,omitempty"` // Zero if no eligible directive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekResponse) Reset() {
	*x = PeekResponse{}
	mi := &file_laneq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekResponse) ProtoMessage() {}

func (x *PeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekResponse.ProtoReflect.Descriptor instead.
func (*PeekResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{6}
}

func (x *PeekResponse) GetDirective() *Directive {
	if x != nil {
		return x.Directive
	}
	return nil
}

// Show request retrieves full details of a directive by ID.
type ShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowRequest) Reset() {
	*x = ShowRequest{}
	mi := &file_laneq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRequest) ProtoMessage() {}

func (x *ShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRequest.ProtoReflect.Descriptor instead.
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{7}
}

func (x *ShowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Show response includes the full directive record.
type ShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directive     *Directive             `protobuf:"bytes,1,opt,name=directive,proto3" json:"directive,omitempty"`
	Thread        []*ThreadItem          `protobuf:"bytes,2,rep,name=thread,proto3" json:"thread,omitempty"` // Child directives in the thread
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowResponse) Reset() {
	*x = ShowResponse{}
	mi := &file_laneq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowResponse) ProtoMessage() {}

func (x *ShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowResponse.ProtoReflect.Descriptor instead.
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{8}
}

func (x *ShowResponse) GetDirective() *Directive {
	if x != nil {
		return x.Directive
	}
	return nil
}

func (x *ShowResponse) GetThread() []*ThreadItem {
	if x != nil {
		return x.Thread
	}
	return nil
}

// ThreadItem is a lightweight reference for thread listings.
type ThreadItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,3,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadItem) Reset() {
	*x = ThreadItem{}
	mi := &file_laneq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadItem) ProtoMessage() {}

func (x *ThreadItem) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadItem.ProtoReflect.Descriptor instead.
func (*ThreadItem) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{9}
}

func (x *ThreadItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThreadItem) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ThreadItem) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

// Listing request queries directives with optional filters.
type ListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllStatuses   bool                   `protobuf:"varint,1,opt,name=all_statuses,json=allStatuses,proto3" json:"all_statuses,omitempty"` // If false, return pending only
	Lane          string                 `protobuf:"bytes,2,opt,name=lane,proto3" json:"lane,omitempty"`                                   // Optional lane filter; "" = all lanes
	Thread        string                 `protobuf:"bytes,3,opt,name=thread,proto3" json:"thread,omitempty"`                               // Optional thread (parent) filter; "" = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingRequest) Reset() {
	*x = ListingRequest{}
	mi := &file_laneq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingRequest) ProtoMessage() {}

func (x *ListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingRequest.ProtoReflect.Descriptor instead.
func (*ListingRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{10}
}

func (x *ListingRequest) GetAllStatuses() bool {
	if x != nil {
		return x.AllStatuses
	}
	return false
}

func (x *ListingRequest) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *ListingRequest) GetThread() string {
	if x != nil {
		return x.Thread
	}
	return ""
}

// Listing response returns matching directives.
type ListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directives    []*Directive           `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingResponse) Reset() {
	*x = ListingResponse{}
	mi := &file_laneq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingResponse) ProtoMessage() {}

func (x *ListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingResponse.ProtoReflect.Descriptor instead.
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{11}
}

func (x *ListingResponse) GetDirectives() []*Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

// Reprioritize request changes a directive's priority.
type ReprioritizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=laneq.v1.Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprioritizeRequest) Reset() {
	*x = ReprioritizeRequest{}
	mi := &file_laneq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprioritizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprioritizeRequest) ProtoMessage() {}

func (x *ReprioritizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprioritizeRequest.ProtoReflect.Descriptor instead.
func (*ReprioritizeRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{12}
}

func (x *ReprioritizeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReprioritizeRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

// Reprioritize response confirms the change.
type ReprioritizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=laneq.v1.Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprioritizeResponse) Reset() {
	*x = ReprioritizeResponse{}
	mi := &file_laneq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprioritizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprioritizeResponse) ProtoMessage() {}

func (x *ReprioritizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprioritizeResponse.ProtoReflect.Descriptor instead.
func (*ReprioritizeResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{13}
}

func (x *ReprioritizeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReprioritizeResponse) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

// SetStatus request changes a directive's status.
type SetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"` // Must be one of: pending (requeue), done, dropped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusRequest) Reset() {
	*x = SetStatusRequest{}
	mi := &file_laneq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusRequest) ProtoMessage() {}

func (x *SetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusRequest.ProtoReflect.Descriptor instead.
func (*SetStatusRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{14}
}

func (x *SetStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetStatusRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// SetStatus response confirms the change.
type SetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusResponse) Reset() {
	*x = SetStatusResponse{}
	mi := &file_laneq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusResponse) ProtoMessage() {}

func (x *SetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusResponse.ProtoReflect.Descriptor instead.
func (*SetStatusResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{15}
}

func (x *SetStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetStatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// Defer request defers a directive until a specified time.
type DeferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UntilUnix     int64                  `protobuf:"varint,2,opt,name=until_unix,json=untilUnix,proto3" json:"until_unix,omitempty"` // Unix timestamp; 0 = use delay
	DelayMs       int64                  `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`       // Alternative to until_unix (milliseconds from now)
	BlockedBy     []string               `protobuf:"bytes,4,rep,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`  // Optional dependency list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeferRequest) Reset() {
	*x = DeferRequest{}
	mi := &file_laneq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeferRequest) ProtoMessage() {}

func (x *DeferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeferRequest.ProtoReflect.Descriptor instead.
func (*DeferRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{16}
}

func (x *DeferRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeferRequest) GetUntilUnix() int64 {
	if x != nil {
		return x.UntilUnix
	}
	return 0
}

func (x *DeferRequest) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *DeferRequest) GetBlockedBy() []string {
	if x != nil {
		return x.BlockedBy
	}
	return nil
}

// Defer response confirms the deferred status.
type DeferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"` // Will be STATUS_DEFERRED
	NotBeforeUnix int64                  `protobuf:"varint,3,opt,name=not_before_unix,json=notBeforeUnix,proto3" json:"not_before_unix,omitempty"`
	BlockedBy     []string               `protobuf:"bytes,4,rep,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeferResponse) Reset() {
	*x = DeferResponse{}
	mi := &file_laneq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeferResponse) ProtoMessage() {}

func (x *DeferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeferResponse.ProtoReflect.Descriptor instead.
func (*DeferResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{17}
}

func (x *DeferResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeferResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *DeferResponse) GetNotBeforeUnix() int64 {
	if x != nil {
		return x.NotBeforeUnix
	}
	return 0
}

func (x *DeferResponse) GetBlockedBy() []string {
	if x != nil {
		return x.BlockedBy
	}
	return nil
}

// Touch request renews a lease on a claimed directive.
type TouchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Consumer        string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`                                         // Consumer holding the lease
	LeaseDurationMs int64                  `protobuf:"varint,3,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"` // New lease duration
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TouchRequest) Reset() {
	*x = TouchRequest{}
	mi := &file_laneq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchRequest) ProtoMessage() {}

func (x *TouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchRequest.ProtoReflect.Descriptor instead.
func (*TouchRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{18}
}

func (x *TouchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TouchRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *TouchRequest) GetLeaseDurationMs() int64 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

// Touch response returns the updated lease expiry.
type TouchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LeaseUntilUnix int64                  `protobuf:"varint,2,opt,name=lease_until_unix,json=leaseUntilUnix,proto3" json:"lease_until_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TouchResponse) Reset() {
	*x = TouchResponse{}
	mi := &file_laneq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchResponse) ProtoMessage() {}

func (x *TouchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchResponse.ProtoReflect.Descriptor instead.
func (*TouchResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{19}
}

func (x *TouchResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TouchResponse) GetLeaseUntilUnix() int64 {
	if x != nil {
		return x.LeaseUntilUnix
	}
	return 0
}

// Reap request reclaims expired leases and stale deferred directives.
type ReapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiredLeases bool                   `protobuf:"varint,1,opt,name=expired_leases,json=expiredLeases,proto3" json:"expired_leases,omitempty"` // If true, reap expired lease_until
	StaleSeconds  int64                  `protobuf:"varint,2,opt,name=stale_seconds,json=staleSeconds,proto3" json:"stale_seconds,omitempty"`    // If > 0, reap deferred items not promoted after this many seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReapRequest) Reset() {
	*x = ReapRequest{}
	mi := &file_laneq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReapRequest) ProtoMessage() {}

func (x *ReapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReapRequest.ProtoReflect.Descriptor instead.
func (*ReapRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{20}
}

func (x *ReapRequest) GetExpiredLeases() bool {
	if x != nil {
		return x.ExpiredLeases
	}
	return false
}

func (x *ReapRequest) GetStaleSeconds() int64 {
	if x != nil {
		return x.StaleSeconds
	}
	return 0
}

// Reap response reports what was reclaimed.
type ReapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`            // "expired_leases" | "stale_deferred" | "both"
	Reclaimed     int32                  `protobuf:"varint,2,opt,name=reclaimed,proto3" json:"reclaimed,omitempty"` // Count of directives reclaimed
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`        // Optional human-readable detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReapResponse) Reset() {
	*x = ReapResponse{}
	mi := &file_laneq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReapResponse) ProtoMessage() {}

func (x *ReapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReapResponse.ProtoReflect.Descriptor instead.
func (*ReapResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{21}
}

func (x *ReapResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ReapResponse) GetReclaimed() int32 {
	if x != nil {
		return x.Reclaimed
	}
	return 0
}

func (x *ReapResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Stats request queries queue statistics.
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_laneq_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{22}
}

// Stats response includes aggregated stats.
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByStatus      map[string]int32       `protobuf:"bytes,1,rep,name=by_status,json=byStatus,proto3" json:"by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Count by status (pending, taken, deferred, done, dropped, parked)
	Consumers     []*ConsumerStats       `protobuf:"bytes,2,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_laneq_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{23}
}

func (x *StatsResponse) GetByStatus() map[string]int32 {
	if x != nil {
		return x.ByStatus
	}
	return nil
}

func (x *StatsResponse) GetConsumers() []*ConsumerStats {
	if x != nil {
		return x.Consumers
	}
	return nil
}

// ConsumerStats tracks activity per consumer.
type ConsumerStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Consumer       string                 `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	ActiveLeases   int32                  `protobuf:"varint,2,opt,name=active_leases,json=activeLeases,proto3" json:"active_leases,omitempty"`
	TotalClaimed   int64                  `protobuf:"varint,3,opt,name=total_claimed,json=totalClaimed,proto3" json:"total_claimed,omitempty"`
	TotalCompleted int64                  `protobuf:"varint,4,opt,name=total_completed,json=totalCompleted,proto3" json:"total_completed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumerStats) Reset() {
	*x = ConsumerStats{}
	mi := &file_laneq_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerStats) ProtoMessage() {}

func (x *ConsumerStats) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerStats.ProtoReflect.Descriptor instead.
func (*ConsumerStats) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{24}
}

func (x *ConsumerStats) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *ConsumerStats) GetActiveLeases() int32 {
	if x != nil {
		return x.ActiveLeases
	}
	return 0
}

func (x *ConsumerStats) GetTotalClaimed() int64 {
	if x != nil {
		return x.TotalClaimed
	}
	return 0
}

func (x *ConsumerStats) GetTotalCompleted() int64 {
	if x != nil {
		return x.TotalCompleted
	}
	return 0
}

// ThreadStatus request queries the status of a directive thread.
type ThreadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Root directive ID of the thread
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadStatusRequest) Reset() {
	*x = ThreadStatusRequest{}
	mi := &file_laneq_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadStatusRequest) ProtoMessage() {}

func (x *ThreadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadStatusRequest.ProtoReflect.Descriptor instead.
func (*ThreadStatusRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{25}
}

func (x *ThreadStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ThreadStatus response includes thread-level aggregation.
type ThreadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"` // "open" (any pending/deferred/taken) | "done" (all completed)
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                        // Total directives in thread (including root)
	Open          int32                  `protobuf:"varint,4,opt,name=open,proto3" json:"open,omitempty"`                          // Pending + deferred + taken count
	OpenItems     []*ThreadItem          `protobuf:"bytes,5,rep,name=open_items,json=openItems,proto3" json:"open_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadStatusResponse) Reset() {
	*x = ThreadStatusResponse{}
	mi := &file_laneq_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadStatusResponse) ProtoMessage() {}

func (x *ThreadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadStatusResponse.ProtoReflect.Descriptor instead.
func (*ThreadStatusResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{26}
}

func (x *ThreadStatusResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ThreadStatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ThreadStatusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ThreadStatusResponse) GetOpen() int32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *ThreadStatusResponse) GetOpenItems() []*ThreadItem {
	if x != nil {
		return x.OpenItems
	}
	return nil
}

// Park request moves a claimed directive into durable hold (parked status).
type ParkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"` // Consumer holding the lease
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkRequest) Reset() {
	*x = ParkRequest{}
	mi := &file_laneq_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkRequest) ProtoMessage() {}

func (x *ParkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkRequest.ProtoReflect.Descriptor instead.
func (*ParkRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{27}
}

func (x *ParkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ParkRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

// Park response confirms the park.
type ParkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"` // Will be STATUS_PARKED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkResponse) Reset() {
	*x = ParkResponse{}
	mi := &file_laneq_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkResponse) ProtoMessage() {}

func (x *ParkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkResponse.ProtoReflect.Descriptor instead.
func (*ParkResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{28}
}

func (x *ParkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ParkResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// Unpark request removes a directive from parked status (returns to pending).
type UnparkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnparkRequest) Reset() {
	*x = UnparkRequest{}
	mi := &file_laneq_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnparkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnparkRequest) ProtoMessage() {}

func (x *UnparkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnparkRequest.ProtoReflect.Descriptor instead.
func (*UnparkRequest) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{29}
}

func (x *UnparkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Unpark response confirms the unpark.
type UnparkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=laneq.v1.Status" json:"status,omitempty"` // Will be STATUS_PENDING
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnparkResponse) Reset() {
	*x = UnparkResponse{}
	mi := &file_laneq_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnparkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnparkResponse) ProtoMessage() {}

func (x *UnparkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laneq_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnparkResponse.ProtoReflect.Descriptor instead.
func (*UnparkResponse) Descriptor() ([]byte, []int) {
	return file_laneq_proto_rawDescGZIP(), []int{30}
}

func (x *UnparkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnparkResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

var File_laneq_proto protoreflect.FileDescriptor

const file_laneq_proto_rawDesc = "" +
	"\n" +
	"\vlaneq.proto\x12\blaneq.v1\"\xd9\x03\n" +
	"\tDirective\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x12.laneq.v1.PriorityR\bpriority\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.laneq.v1.StatusR\x06status\x12\x12\n" +
	"\x04lane\x18\x05 \x01(\tR\x04lane\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12\"\n" +
	"\rtaken_at_unix\x18\a \x01(\x03R\vtakenAtUnix\x12 \n" +
	"\fdone_at_unix\x18\b \x01(\x03R\n" +
	"doneAtUnix\x12\x19\n" +
	"\btaken_by\x18\t \x01(\tR\atakenBy\x12(\n" +
	"\x10lease_until_unix\x18\n" +
	" \x01(\x03R\x0eleaseUntilUnix\x12#\n" +
	"\rrequeue_count\x18\v \x01(\x05R\frequeueCount\x12\x1b\n" +
	"\tparent_id\x18\f \x01(\tR\bparentId\x12&\n" +
	"\x0fnot_before_unix\x18\r \x01(\x03R\rnotBeforeUnix\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x0e \x03(\tR\tblockedBy\"\x82\x01\n" +
	"\vPushRequest\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12.\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x12.laneq.v1.PriorityR\bpriority\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04lane\x18\x04 \x01(\tR\x04lane\"\xc3\x01\n" +
	"\fPushResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x12.laneq.v1.PriorityR\bpriority\x12\x12\n" +
	"\x04lane\x18\x03 \x01(\tR\x04lane\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.laneq.v1.StatusR\x06status\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\"\x97\x01\n" +
	"\vTakeRequest\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\x12\x12\n" +
	"\x04lane\x18\x02 \x01(\tR\x04lane\x12*\n" +
	"\x11lease_duration_ms\x18\x03 \x01(\x03R\x0fleaseDurationMs\x12,\n" +
	"\x12reap_stale_seconds\x18\x04 \x01(\x03R\x10reapStaleSeconds\"q\n" +
	"\fTakeResponse\x121\n" +
	"\tdirective\x18\x01 \x01(\v2\x13.laneq.v1.DirectiveR\tdirective\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\x12\x12\n" +
	"\x04lane\x18\x03 \x01(\tR\x04lane\"!\n" +
	"\vPeekRequest\x12\x12\n" +
	"\x04lane\x18\x01 \x01(\tR\x04lane\"A\n" +
	"\fPeekResponse\x121\n" +
	"\tdirective\x18\x01 \x01(\v2\x13.laneq.v1.DirectiveR\tdirective\"\x1d\n" +
	"\vShowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\fShowResponse\x121\n" +
	"\tdirective\x18\x01 \x01(\v2\x13.laneq.v1.DirectiveR\tdirective\x12,\n" +
	"\x06thread\x18\x02 \x03(\v2\x14.laneq.v1.ThreadItemR\x06thread\"n\n" +
	"\n" +
	"ThreadItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.laneq.v1.StatusR\x06status\x12&\n" +
	"\x0fcreated_at_unix\x18\x03 \x01(\x03R\rcreatedAtUnix\"_\n" +
	"\x0eListingRequest\x12!\n" +
	"\fall_statuses\x18\x01 \x01(\bR\vallStatuses\x12\x12\n" +
	"\x04lane\x18\x02 \x01(\tR\x04lane\x12\x16\n" +
	"\x06thread\x18\x03 \x01(\tR\x06thread\"F\n" +
	"\x0fListingResponse\x123\n" +
	"\n" +
	"directives\x18\x01 \x03(\v2\x13.laneq.v1.DirectiveR\n" +
	"directives\"U\n" +
	"\x13ReprioritizeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x12.laneq.v1.PriorityR\bpriority\"V\n" +
	"\x14ReprioritizeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x12.laneq.v1.PriorityR\bpriority\"L\n" +
	"\x10SetStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.laneq.v1.StatusR\x06status\"M\n" +
	"\x11SetStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.laneq.v1.StatusR\x06status\"w\n" +
	"\fDeferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"until_unix\x18\x02 \x01(\x03R\tuntilUnix\x12\x19\n" +
	"\bdelay_ms\x18\x03 \x01(\x03R\adelayMs\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x04 \x03(\tR\tblockedBy\"\x90\x01\n" +
	"\rDeferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.laneq.v1.StatusR\x06status\x12&\n" +
	"\x0fnot_before_unix\x18\x03 \x01(\x03R\rnotBeforeUnix\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x04 \x03(\tR\tblockedBy\"f\n" +
	"\fTouchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\x12*\n" +
	"\x11lease_duration_ms\x18\x03 \x01(\x03R\x0fleaseDurationMs\"I\n" +
	"\rTouchResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10lease_until_unix\x18\x02 \x01(\x03R\x0eleaseUntilUnix\"Y\n" +
	"\vReapRequest\x12%\n" +
	"\x0eexpired_leases\x18\x01 \x01(\bR\rexpiredLeases\x12#\n" +
	"\rstale_seconds\x18\x02 \x01(\x03R\fstaleSeconds\"X\n" +
	"\fReapResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1c\n" +
	"\treclaimed\x18\x02 \x01(\x05R\treclaimed\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\x0e\n" +
	"\fStatsRequest\"\xc7\x01\n" +
	"\rStatsResponse\x12B\n" +
	"\tby_status\x18\x01 \x03(\v2%.laneq.v1.StatsResponse.ByStatusEntryR\bbyStatus\x125\n" +
	"\tconsumers\x18\x02 \x03(\v2\x17.laneq.v1.ConsumerStatsR\tconsumers\x1a;\n" +
	"\rByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9e\x01\n" +
	"\rConsumerStats\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\x12#\n" +
	"\ractive_leases\x18\x02 \x01(\x05R\factiveLeases\x12#\n" +
	"\rtotal_claimed\x18\x03 \x01(\x03R\ftotalClaimed\x12'\n" +
	"\x0ftotal_completed\x18\x04 \x01(\x03R\x0etotalCompleted\"%\n" +
	"\x13ThreadStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb3\x01\n" +
	"\x14ThreadStatusResponse\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.laneq.v1.StatusR\x06status\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x05R\x04open\x123\n" +
	"\n" +
	"open_items\x18\x05 \x03(\v2\x14.laneq.v1.ThreadItemR\topenItems\"9\n" +
	"\vParkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\"H\n" +
	"\fParkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.laneq.v1.StatusR\x06status\"\x1f\n" +
	"\rUnparkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x0eUnparkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.laneq.v1.StatusR\x06status*W\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vPRIORITY_P0\x10\x01\x12\x0f\n" +
	"\vPRIORITY_P1\x10\x02\x12\x0f\n" +
	"\vPRIORITY_P2\x10\x03*\x93\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x10\n" +
	"\fSTATUS_TAKEN\x10\x02\x12\x13\n" +
	"\x0fSTATUS_DEFERRED\x10\x03\x12\x0f\n" +
	"\vSTATUS_DONE\x10\x04\x12\x12\n" +
	"\x0eSTATUS_DROPPED\x10\x05\x12\x11\n" +
	"\rSTATUS_PARKED\x10\x062\xe0\x06\n" +
	"\x05Laneq\x125\n" +
	"\x04Push\x12\x15.laneq.v1.PushRequest\x1a\x16.laneq.v1.PushResponse\x125\n" +
	"\x04Take\x12\x15.laneq.v1.TakeRequest\x1a\x16.laneq.v1.TakeResponse\x125\n" +
	"\x04Peek\x12\x15.laneq.v1.PeekRequest\x1a\x16.laneq.v1.PeekResponse\x125\n" +
	"\x04Show\x12\x15.laneq.v1.ShowRequest\x1a\x16.laneq.v1.ShowResponse\x12>\n" +
	"\aListing\x12\x18.laneq.v1.ListingRequest\x1a\x19.laneq.v1.ListingResponse\x12M\n" +
	"\fReprioritize\x12\x1d.laneq.v1.ReprioritizeRequest\x1a\x1e.laneq.v1.ReprioritizeResponse\x12D\n" +
	"\tSetStatus\x12\x1a.laneq.v1.SetStatusRequest\x1a\x1b.laneq.v1.SetStatusResponse\x128\n" +
	"\x05Defer\x12\x16.laneq.v1.DeferRequest\x1a\x17.laneq.v1.DeferResponse\x128\n" +
	"\x05Touch\x12\x16.laneq.v1.TouchRequest\x1a\x17.laneq.v1.TouchResponse\x125\n" +
	"\x04Reap\x12\x15.laneq.v1.ReapRequest\x1a\x16.laneq.v1.ReapResponse\x128\n" +
	"\x05Stats\x12\x16.laneq.v1.StatsRequest\x1a\x17.laneq.v1.StatsResponse\x12M\n" +
	"\fThreadStatus\x12\x1d.laneq.v1.ThreadStatusRequest\x1a\x1e.laneq.v1.ThreadStatusResponse\x125\n" +
	"\x04Park\x12\x15.laneq.v1.ParkRequest\x1a\x16.laneq.v1.ParkResponse\x12;\n" +
	"\x06Unpark\x12\x17.laneq.v1.UnparkRequest\x1a\x18.laneq.v1.UnparkResponseB9Z7github.com/agent-sandbox/incus-dispatcher/queue/laneqpbb\x06proto3"

var (
	file_laneq_proto_rawDescOnce sync.Once
	file_laneq_proto_rawDescData []byte
)

func file_laneq_proto_rawDescGZIP() []byte {
	file_laneq_proto_rawDescOnce.Do(func() {
		file_laneq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laneq_proto_rawDesc), len(file_laneq_proto_rawDesc)))
	})
	return file_laneq_proto_rawDescData
}

var file_laneq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_laneq_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_laneq_proto_goTypes = []any{
	(Priority)(0),                // 0: laneq.v1.Priority
	(Status)(0),                  // 1: laneq.v1.Status
	(*Directive)(nil),            // 2: laneq.v1.Directive
	(*PushRequest)(nil),          // 3: laneq.v1.PushRequest
	(*PushResponse)(nil),         // 4: laneq.v1.PushResponse
	(*TakeRequest)(nil),          // 5: laneq.v1.TakeRequest
	(*TakeResponse)(nil),         // 6: laneq.v1.TakeResponse
	(*PeekRequest)(nil),          // 7: laneq.v1.PeekRequest
	(*PeekResponse)(nil),         // 8: laneq.v1.PeekResponse
	(*ShowRequest)(nil),          // 9: laneq.v1.ShowRequest
	(*ShowResponse)(nil),         // 10: laneq.v1.ShowResponse
	(*ThreadItem)(nil),           // 11: laneq.v1.ThreadItem
	(*ListingRequest)(nil),       // 12: laneq.v1.ListingRequest
	(*ListingResponse)(nil),      // 13: laneq.v1.ListingResponse
	(*ReprioritizeRequest)(nil),  // 14: laneq.v1.ReprioritizeRequest
	(*ReprioritizeResponse)(nil), // 15: laneq.v1.ReprioritizeResponse
	(*SetStatusRequest)(nil),     // 16: laneq.v1.SetStatusRequest
	(*SetStatusResponse)(nil),    // 17: laneq.v1.SetStatusResponse
	(*DeferRequest)(nil),         // 18: laneq.v1.DeferRequest
	(*DeferResponse)(nil),        // 19: laneq.v1.DeferResponse
	(*TouchRequest)(nil),         // 20: laneq.v1.TouchRequest
	(*TouchResponse)(nil),        // 21: laneq.v1.TouchResponse
	(*ReapRequest)(nil),          // 22: laneq.v1.ReapRequest
	(*ReapResponse)(nil),         // 23: laneq.v1.ReapResponse
	(*StatsRequest)(nil),         // 24: laneq.v1.StatsRequest
	(*StatsResponse)(nil),        // 25: laneq.v1.StatsResponse
	(*ConsumerStats)(nil),        // 26: laneq.v1.ConsumerStats
	(*ThreadStatusRequest)(nil),  // 27: laneq.v1.ThreadStatusRequest
	(*ThreadStatusResponse)(nil), // 28: laneq.v1.ThreadStatusResponse
	(*ParkRequest)(nil),          // 29: laneq.v1.ParkRequest
	(*ParkResponse)(nil),         // 30: laneq.v1.ParkResponse
	(*UnparkRequest)(nil),        // 31: laneq.v1.UnparkRequest
	(*UnparkResponse)(nil),       // 32: laneq.v1.UnparkResponse
	nil,                          // 33: laneq.v1.StatsResponse.ByStatusEntry
}
var file_laneq_proto_depIdxs = []int32{
	0,  // 0: laneq.v1.Directive.priority:type_name -> laneq.v1.Priority
	1,  // 1: laneq.v1.Directive.status:type_name -> laneq.v1.Status
	0,  // 2: laneq.v1.PushRequest.priority:type_name -> laneq.v1.Priority
	0,  // 3: laneq.v1.PushResponse.priority:type_name -> laneq.v1.Priority
	1,  // 4: laneq.v1.PushResponse.status:type_name -> laneq.v1.Status
	2,  // 5: laneq.v1.TakeResponse.directive:type_name -> laneq.v1.Directive
	2,  // 6: laneq.v1.PeekResponse.directive:type_name -> laneq.v1.Directive
	2,  // 7: laneq.v1.ShowResponse.directive:type_name -> laneq.v1.Directive
	11, // 8: laneq.v1.ShowResponse.thread:type_name -> laneq.v1.ThreadItem
	1,  // 9: laneq.v1.ThreadItem.status:type_name -> laneq.v1.Status
	2,  // 10: laneq.v1.ListingResponse.directives:type_name -> laneq.v1.Directive
	0,  // 11: laneq.v1.ReprioritizeRequest.priority:type_name -> laneq.v1.Priority
	0,  // 12: laneq.v1.ReprioritizeResponse.priority:type_name -> laneq.v1.Priority
	1,  // 13: laneq.v1.SetStatusRequest.status:type_name -> laneq.v1.Status
	1,  // 14: laneq.v1.SetStatusResponse.status:type_name -> laneq.v1.Status
	1,  // 15: laneq.v1.DeferResponse.status:type_name -> laneq.v1.Status
	33, // 16: laneq.v1.StatsResponse.by_status:type_name -> laneq.v1.StatsResponse.ByStatusEntry
	26, // 17: laneq.v1.StatsResponse.consumers:type_name -> laneq.v1.ConsumerStats
	1,  // 18: laneq.v1.ThreadStatusResponse.status:type_name -> laneq.v1.Status
	11, // 19: laneq.v1.ThreadStatusResponse.open_items:type_name -> laneq.v1.ThreadItem
	1,  // 20: laneq.v1.ParkResponse.status:type_name -> laneq.v1.Status
	1,  // 21: laneq.v1.UnparkResponse.status:type_name -> laneq.v1.Status
	3,  // 22: laneq.v1.Laneq.Push:input_type -> laneq.v1.PushRequest
	5,  // 23: laneq.v1.Laneq.Take:input_type -> laneq.v1.TakeRequest
	7,  // 24: laneq.v1.Laneq.Peek:input_type -> laneq.v1.PeekRequest
	9,  // 25: laneq.v1.Laneq.Show:input_type -> laneq.v1.ShowRequest
	12, // 26: laneq.v1.Laneq.Listing:input_type -> laneq.v1.ListingRequest
	14, // 27: laneq.v1.Laneq.Reprioritize:input_type -> laneq.v1.ReprioritizeRequest
	16, // 28: laneq.v1.Laneq.SetStatus:input_type -> laneq.v1.SetStatusRequest
	18, // 29: laneq.v1.Laneq.Defer:input_type -> laneq.v1.DeferRequest
	20, // 30: laneq.v1.Laneq.Touch:input_type -> laneq.v1.TouchRequest
	22, // 31: laneq.v1.Laneq.Reap:input_type -> laneq.v1.ReapRequest
	24, // 32: laneq.v1.Laneq.Stats:input_type -> laneq.v1.StatsRequest
	27, // 33: laneq.v1.Laneq.ThreadStatus:input_type -> laneq.v1.ThreadStatusRequest
	29, // 34: laneq.v1.Laneq.Park:input_type -> laneq.v1.ParkRequest
	31, // 35: laneq.v1.Laneq.Unpark:input_type -> laneq.v1.UnparkRequest
	4,  // 36: laneq.v1.Laneq.Push:output_type -> laneq.v1.PushResponse
	6,  // 37: laneq.v1.Laneq.Take:output_type -> laneq.v1.TakeResponse
	8,  // 38: laneq.v1.Laneq.Peek:output_type -> laneq.v1.PeekResponse
	10, // 39: laneq.v1.Laneq.Show:output_type -> laneq.v1.ShowResponse
	13, // 40: laneq.v1.Laneq.Listing:output_type -> laneq.v1.ListingResponse
	15, // 41: laneq.v1.Laneq.Reprioritize:output_type -> laneq.v1.ReprioritizeResponse
	17, // 42: laneq.v1.Laneq.SetStatus:output_type -> laneq.v1.SetStatusResponse
	19, // 43: laneq.v1.Laneq.Defer:output_type -> laneq.v1.DeferResponse
	21, // 44: laneq.v1.Laneq.Touch:output_type -> laneq.v1.TouchResponse
	23, // 45: laneq.v1.Laneq.Reap:output_type -> laneq.v1.ReapResponse
	25, // 46: laneq.v1.Laneq.Stats:output_type -> laneq.v1.StatsResponse
	28, // 47: laneq.v1.Laneq.ThreadStatus:output_type -> laneq.v1.ThreadStatusResponse
	30, // 48: laneq.v1.Laneq.Park:output_type -> laneq.v1.ParkResponse
	32, // 49: laneq.v1.Laneq.Unpark:output_type -> laneq.v1.UnparkResponse
	36, // [36:50] is the sub-list for method output_type
	22, // [22:36] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_laneq_proto_init() }
func file_laneq_proto_init() {
	if File_laneq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laneq_proto_rawDesc), len(file_laneq_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_laneq_proto_goTypes,
		DependencyIndexes: file_laneq_proto_depIdxs,
		EnumInfos:         file_laneq_proto_enumTypes,
		MessageInfos:      file_laneq_proto_msgTypes,
	}.Build()
	File_laneq_proto = out.File
	file_laneq_proto_goTypes = nil
	file_laneq_proto_depIdxs = nil
}
