// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: laneq.proto

package laneqpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Laneq_Push_FullMethodName         = "/laneq.v1.Laneq/Push"
	Laneq_Take_FullMethodName         = "/laneq.v1.Laneq/Take"
	Laneq_Peek_FullMethodName         = "/laneq.v1.Laneq/Peek"
	Laneq_Show_FullMethodName         = "/laneq.v1.Laneq/Show"
	Laneq_Listing_FullMethodName      = "/laneq.v1.Laneq/Listing"
	Laneq_Reprioritize_FullMethodName = "/laneq.v1.Laneq/Reprioritize"
	Laneq_SetStatus_FullMethodName    = "/laneq.v1.Laneq/SetStatus"
	Laneq_Defer_FullMethodName        = "/laneq.v1.Laneq/Defer"
	Laneq_Touch_FullMethodName        = "/laneq.v1.Laneq/Touch"
	Laneq_Reap_FullMethodName         = "/laneq.v1.Laneq/Reap"
	Laneq_Stats_FullMethodName        = "/laneq.v1.Laneq/Stats"
	Laneq_ThreadStatus_FullMethodName = "/laneq.v1.Laneq/ThreadStatus"
	Laneq_Park_FullMethodName         = "/laneq.v1.Laneq/Park"
	Laneq_Unpark_FullMethodName       = "/laneq.v1.Laneq/Unpark"
)

// LaneqClient is the client API for Laneq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Laneq service definition.
type LaneqClient interface {
	// Push enqueues a new directive with the specified priority and lane.
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	// Take atomically claims the highest-priority eligible pending directive.
	// Returns an empty Directive if no eligible directive exists.
	Take(ctx context.Context, in *TakeRequest, opts ...grpc.CallOption) (*TakeResponse, error)
	// Peek returns the next eligible directive without claiming it.
	// Returns an empty Directive if no eligible directive exists.
	Peek(ctx context.Context, in *PeekRequest, opts ...grpc.CallOption) (*PeekResponse, error)
	// Show retrieves full details of a directive by ID, including its thread.
	Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error)
	// Listing queries directives with optional filters (status, lane, thread).
	Listing(ctx context.Context, in *ListingRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	// Reprioritize changes a directive's priority.
	Reprioritize(ctx context.Context, in *ReprioritizeRequest, opts ...grpc.CallOption) (*ReprioritizeResponse, error)
	// SetStatus changes a directive's status (pending, done, dropped).
	SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*SetStatusResponse, error)
	// Defer defers a directive until a specified time or delay, optionally blocking on dependencies.
	Defer(ctx context.Context, in *DeferRequest, opts ...grpc.CallOption) (*DeferResponse, error)
	// Touch renews the lease on a claimed directive.
	Touch(ctx context.Context, in *TouchRequest, opts ...grpc.CallOption) (*TouchResponse, error)
	// Reap reclaims expired leases and stale deferred directives.
	Reap(ctx context.Context, in *ReapRequest, opts ...grpc.CallOption) (*ReapResponse, error)
	// Stats returns queue statistics (counts by status, consumer activity).
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// ThreadStatus queries the status of a directive thread (parent + children).
	ThreadStatus(ctx context.Context, in *ThreadStatusRequest, opts ...grpc.CallOption) (*ThreadStatusResponse, error)
	// Park moves a claimed directive into durable hold (excluded from claim/peek/reap).
	// Must be called with a valid lease (consumer + active lease_until).
	Park(ctx context.Context, in *ParkRequest, opts ...grpc.CallOption) (*ParkResponse, error)
	// Unpark removes a directive from parked status (returns to pending).
	Unpark(ctx context.Context, in *UnparkRequest, opts ...grpc.CallOption) (*UnparkResponse, error)
}

type laneqClient struct {
	cc grpc.ClientConnInterface
}

func NewLaneqClient(cc grpc.ClientConnInterface) LaneqClient {
	return &laneqClient{cc}
}

func (c *laneqClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, Laneq_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Take(ctx context.Context, in *TakeRequest, opts ...grpc.CallOption) (*TakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeResponse)
	err := c.cc.Invoke(ctx, Laneq_Take_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Peek(ctx context.Context, in *PeekRequest, opts ...grpc.CallOption) (*PeekResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeekResponse)
	err := c.cc.Invoke(ctx, Laneq_Peek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowResponse)
	err := c.cc.Invoke(ctx, Laneq_Show_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Listing(ctx context.Context, in *ListingRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, Laneq_Listing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Reprioritize(ctx context.Context, in *ReprioritizeRequest, opts ...grpc.CallOption) (*ReprioritizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReprioritizeResponse)
	err := c.cc.Invoke(ctx, Laneq_Reprioritize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*SetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStatusResponse)
	err := c.cc.Invoke(ctx, Laneq_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Defer(ctx context.Context, in *DeferRequest, opts ...grpc.CallOption) (*DeferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeferResponse)
	err := c.cc.Invoke(ctx, Laneq_Defer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Touch(ctx context.Context, in *TouchRequest, opts ...grpc.CallOption) (*TouchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TouchResponse)
	err := c.cc.Invoke(ctx, Laneq_Touch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Reap(ctx context.Context, in *ReapRequest, opts ...grpc.CallOption) (*ReapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReapResponse)
	err := c.cc.Invoke(ctx, Laneq_Reap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, Laneq_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) ThreadStatus(ctx context.Context, in *ThreadStatusRequest, opts ...grpc.CallOption) (*ThreadStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThreadStatusResponse)
	err := c.cc.Invoke(ctx, Laneq_ThreadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Park(ctx context.Context, in *ParkRequest, opts ...grpc.CallOption) (*ParkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParkResponse)
	err := c.cc.Invoke(ctx, Laneq_Park_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laneqClient) Unpark(ctx context.Context, in *UnparkRequest, opts ...grpc.CallOption) (*UnparkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnparkResponse)
	err := c.cc.Invoke(ctx, Laneq_Unpark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaneqServer is the server API for Laneq service.
// All implementations must embed UnimplementedLaneqServer
// for forward compatibility.
//
// Laneq service definition.
type LaneqServer interface {
	// Push enqueues a new directive with the specified priority and lane.
	Push(context.Context, *PushRequest) (*PushResponse, error)
	// Take atomically claims the highest-priority eligible pending directive.
	// Returns an empty Directive if no eligible directive exists.
	Take(context.Context, *TakeRequest) (*TakeResponse, error)
	// Peek returns the next eligible directive without claiming it.
	// Returns an empty Directive if no eligible directive exists.
	Peek(context.Context, *PeekRequest) (*PeekResponse, error)
	// Show retrieves full details of a directive by ID, including its thread.
	Show(context.Context, *ShowRequest) (*ShowResponse, error)
	// Listing queries directives with optional filters (status, lane, thread).
	Listing(context.Context, *ListingRequest) (*ListingResponse, error)
	// Reprioritize changes a directive's priority.
	Reprioritize(context.Context, *ReprioritizeRequest) (*ReprioritizeResponse, error)
	// SetStatus changes a directive's status (pending, done, dropped).
	SetStatus(context.Context, *SetStatusRequest) (*SetStatusResponse, error)
	// Defer defers a directive until a specified time or delay, optionally blocking on dependencies.
	Defer(context.Context, *DeferRequest) (*DeferResponse, error)
	// Touch renews the lease on a claimed directive.
	Touch(context.Context, *TouchRequest) (*TouchResponse, error)
	// Reap reclaims expired leases and stale deferred directives.
	Reap(context.Context, *ReapRequest) (*ReapResponse, error)
	// Stats returns queue statistics (counts by status, consumer activity).
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// ThreadStatus queries the status of a directive thread (parent + children).
	ThreadStatus(context.Context, *ThreadStatusRequest) (*ThreadStatusResponse, error)
	// Park moves a claimed directive into durable hold (excluded from claim/peek/reap).
	// Must be called with a valid lease (consumer + active lease_until).
	Park(context.Context, *ParkRequest) (*ParkResponse, error)
	// Unpark removes a directive from parked status (returns to pending).
	Unpark(context.Context, *UnparkRequest) (*UnparkResponse, error)
	mustEmbedUnimplementedLaneqServer()
}

// UnimplementedLaneqServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLaneqServer struct{}

func (UnimplementedLaneqServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedLaneqServer) Take(context.Context, *TakeRequest) (*TakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Take not implemented")
}
func (UnimplementedLaneqServer) Peek(context.Context, *PeekRequest) (*PeekResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Peek not implemented")
}
func (UnimplementedLaneqServer) Show(context.Context, *ShowRequest) (*ShowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Show not implemented")
}
func (UnimplementedLaneqServer) Listing(context.Context, *ListingRequest) (*ListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Listing not implemented")
}
func (UnimplementedLaneqServer) Reprioritize(context.Context, *ReprioritizeRequest) (*ReprioritizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reprioritize not implemented")
}
func (UnimplementedLaneqServer) SetStatus(context.Context, *SetStatusRequest) (*SetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedLaneqServer) Defer(context.Context, *DeferRequest) (*DeferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Defer not implemented")
}
func (UnimplementedLaneqServer) Touch(context.Context, *TouchRequest) (*TouchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Touch not implemented")
}
func (UnimplementedLaneqServer) Reap(context.Context, *ReapRequest) (*ReapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reap not implemented")
}
func (UnimplementedLaneqServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedLaneqServer) ThreadStatus(context.Context, *ThreadStatusRequest) (*ThreadStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ThreadStatus not implemented")
}
func (UnimplementedLaneqServer) Park(context.Context, *ParkRequest) (*ParkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Park not implemented")
}
func (UnimplementedLaneqServer) Unpark(context.Context, *UnparkRequest) (*UnparkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unpark not implemented")
}
func (UnimplementedLaneqServer) mustEmbedUnimplementedLaneqServer() {}
func (UnimplementedLaneqServer) testEmbeddedByValue()               {}

// UnsafeLaneqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaneqServer will
// result in compilation errors.
type UnsafeLaneqServer interface {
	mustEmbedUnimplementedLaneqServer()
}

func RegisterLaneqServer(s grpc.ServiceRegistrar, srv LaneqServer) {
	// If the following call panics, it indicates UnimplementedLaneqServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Laneq_ServiceDesc, srv)
}

func _Laneq_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Take_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Take(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Take_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Take(ctx, req.(*TakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Peek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Peek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Peek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Peek(ctx, req.(*PeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Show_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Show(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Listing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Listing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Listing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Listing(ctx, req.(*ListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Reprioritize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReprioritizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Reprioritize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Reprioritize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Reprioritize(ctx, req.(*ReprioritizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).SetStatus(ctx, req.(*SetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Defer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Defer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Defer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Defer(ctx, req.(*DeferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Touch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Touch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Touch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Touch(ctx, req.(*TouchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Reap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Reap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Reap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Reap(ctx, req.(*ReapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_ThreadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).ThreadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_ThreadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).ThreadStatus(ctx, req.(*ThreadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Park_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Park(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Park_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Park(ctx, req.(*ParkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Laneq_Unpark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnparkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaneqServer).Unpark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Laneq_Unpark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaneqServer).Unpark(ctx, req.(*UnparkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Laneq_ServiceDesc is the grpc.ServiceDesc for Laneq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Laneq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "laneq.v1.Laneq",
	HandlerType: (*LaneqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Laneq_Push_Handler,
		},
		{
			MethodName: "Take",
			Handler:    _Laneq_Take_Handler,
		},
		{
			MethodName: "Peek",
			Handler:    _Laneq_Peek_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _Laneq_Show_Handler,
		},
		{
			MethodName: "Listing",
			Handler:    _Laneq_Listing_Handler,
		},
		{
			MethodName: "Reprioritize",
			Handler:    _Laneq_Reprioritize_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _Laneq_SetStatus_Handler,
		},
		{
			MethodName: "Defer",
			Handler:    _Laneq_Defer_Handler,
		},
		{
			MethodName: "Touch",
			Handler:    _Laneq_Touch_Handler,
		},
		{
			MethodName: "Reap",
			Handler:    _Laneq_Reap_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Laneq_Stats_Handler,
		},
		{
			MethodName: "ThreadStatus",
			Handler:    _Laneq_ThreadStatus_Handler,
		},
		{
			MethodName: "Park",
			Handler:    _Laneq_Park_Handler,
		},
		{
			MethodName: "Unpark",
			Handler:    _Laneq_Unpark_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "laneq.proto",
}
