#!/usr/bin/env bash
# build-golden.sh — build + publish the FULL NixOS golden worker image (STORY-0075 AC-1 +
# STORY-0077). Cluster-resident: runs against an Incus remote (the Mac has no Nix).
#
#   bash fleet-worker/build-golden.sh [build-container] [remote] [image-alias]
#       build-container  default: fleet-golden-build
#       remote           default: ndn-desktop
#       image-alias      default: fleet-golden
#
# What it does (the FULL golden contract):
#   1. push the fleet-worker flake → /root/fleet-worker + /etc/fleet-worker on the container
#   2. build the curated skills copy-tree bundle (.#agent-skills-bundle-etc) → store path
#   3. wire that store path into /etc/nixos/golden-skills.nix (generated)
#   4. assemble /etc/nixos: worker-container.nix + golden.nix + golden-full.nix +
#      configuration.nix (imports golden-full.nix), keeping the image's generated incus.nix
#   5. build the system closure (substitution-only) + activate (bootloader-free:
#      nix-env --set + switch-to-configuration switch — LXC has no bootloader)
#   6. REALIZE the devShell closure (`nix develop /etc/fleet-worker -c true`) so a copy runs
#      the runner with zero build (AC-1)
#   7. publish the container as the <image-alias> image (stop → delete old alias → publish)
#
# Idempotent: re-running rebuilds + republishes from the same container.
set -euo pipefail

C="${1:-fleet-golden-build}"
REMOTE="${2:-ndn-desktop}"
ALIAS="${3:-fleet-golden}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
NIXFLAGS="--extra-experimental-features 'nix-command flakes' --accept-flake-config --no-sandbox"

say() { printf '\n=== %s ===\n' "$*"; }
xc()  { incus exec "${REMOTE}:${C}" -- bash -lc "$*"; }

say "1/7 push fleet-worker flake to ${C}"
incus exec "${REMOTE}:${C}" -- bash -lc 'rm -rf /root/fleet-worker /etc/fleet-worker && mkdir -p /root/fleet-worker /etc/fleet-worker'
for dst in /root/fleet-worker /etc/fleet-worker; do
  COPYFILE_DISABLE=1 tar --no-mac-metadata -C "$REPO_ROOT/fleet-worker" --exclude='*.DS_Store' --exclude='spikes' --exclude='cluster-tests' -czf - . \
    | incus exec "${REMOTE}:${C}" -- bash -lc "tar -C ${dst} --warning=no-unknown-keyword -xzf -"
done

say "2/7 build curated skills copy-tree bundle"
BUNDLE="$(xc "cd /root/fleet-worker && nix build --no-link --print-out-paths .#agent-skills-bundle-etc ${NIXFLAGS} 2>/dev/null | tail -1")"
[ -n "$BUNDLE" ] || { echo "FAIL: bundle build produced no store path"; exit 1; }
echo "bundle = $BUNDLE"

say "3/7 generate /etc/nixos/golden-skills.nix (skills discovery path)"
xc "cat > /etc/nixos/golden-skills.nix <<NIXEOF
# GENERATED by build-golden.sh — pins the curated skills copy-tree (STORY-0077 AC-3/AC-4).
{ ... }:
{
  environment.etc.\"claude/skills\".source = ${BUNDLE};
}
NIXEOF"

say "4/7 assemble /etc/nixos worker config"
for f in worker-container.nix golden.nix golden-full.nix; do
  incus file push "$HERE/$f" "${REMOTE}:${C}/etc/nixos/$f"
done
xc "cat > /etc/nixos/configuration.nix <<'NIXEOF'
# GENERATED by build-golden.sh — the FULL golden entrypoint (STORY-0075/0077, ITER-0005c).
{ ... }:
{
  imports = [ ./golden-full.nix ];
}
NIXEOF"

say "5/7 build + activate system closure (bootloader-free)"
# The fresh container has no nixos channel, so <nixpkgs/nixos> is unresolved. Pin NIX_PATH to
# the flake's locked nixpkgs (deterministic; no channel fetch) for the bootstrap rebuild.
NPKGS="$(xc "nix eval --raw --impure --extra-experimental-features 'nix-command flakes' --accept-flake-config --expr 'toString (builtins.getFlake \"path:/root/fleet-worker\").inputs.nixpkgs'")"
[ -n "$NPKGS" ] || { echo "FAIL: could not resolve flake nixpkgs for NIX_PATH"; exit 1; }
echo "NIX_PATH nixpkgs = $NPKGS"
xc "export NIX_CONFIG='experimental-features = nix-command flakes
sandbox = false'
cd /etc/nixos
nixos-rebuild build -I nixpkgs=${NPKGS} -I nixos-config=/etc/nixos/configuration.nix 2>&1 | tail -8"
xc "nix-env -p /nix/var/nix/profiles/system --set /etc/nixos/result"
xc "/etc/nixos/result/bin/switch-to-configuration switch 2>&1 | tail -8 || /etc/nixos/result/bin/switch-to-configuration boot 2>&1 | tail -8"

say "6/7 realize devShell closure (zero-build runner per task)"
xc "nix develop /etc/fleet-worker ${NIXFLAGS} -c true 2>&1 | tail -3 || true"

say "verify on the build container"
xc "echo marker: \$(cat /etc/fleet-golden-version)
echo -n 'skills SKILL.md: '; find -L /etc/claude/skills -name SKILL.md 2>/dev/null | wc -l
echo -n 'symlinked SKILL.md: '; find /etc/claude/skills -name SKILL.md -type l 2>/dev/null | wc -l
for t in claude lean-ctx go make git; do
  if command -v \$t >/dev/null 2>&1 || nix develop /etc/fleet-worker ${NIXFLAGS} -c command -v \$t >/dev/null 2>&1; then echo \"tool ok: \$t\"; else echo \"tool MISSING: \$t\"; fi
done"

say "7/7 publish ${ALIAS} image"
incus stop "${REMOTE}:${C}"
incus image alias delete "${REMOTE}:${ALIAS}" 2>/dev/null || true
incus publish "${REMOTE}:${C}" --alias "${ALIAS}" --reuse \
  --compression zstd \
  description="FULL NixOS golden (STORY-0075/0077): realized toolchain + 13 curated skills"
incus start "${REMOTE}:${C}"
say "done — published ${REMOTE}:${ALIAS}"
