# fleet-worker/golden-full.nix
#
# STORY-0075 (FULL golden) + STORY-0077 (curated skills) — the FULL golden worker image,
# extending the immutable substrate (golden.nix → worker-container.nix). Where the minimal
# slice (ITER-0000) substituted the toolchain at *task* time via `nix develop`, the FULL
# golden REALIZES that closure into the image's store once, so a launched copy runs
# `nix develop` with zero build (AC-1: build once, `incus copy` per task = zero rebuild), and
# bakes the curated skills at the discovery path (STORY-0077 AC-3/AC-4).
#
# This module is COPIED into /etc/nixos alongside golden.nix + worker-container.nix +
# the image's generated incus.nix (per worker-container.nix's apply note); the skills bundle
# store path is wired in by build-golden.sh via the generated ./golden-skills.nix import.
{ lib, pkgs, ... }:

{
  imports = [
    ./golden.nix
    # Generated by build-golden.sh: sets environment.etc."claude/skills".source to the
    # copy-tree bundle store path (`nix build .#agent-skills-bundle-etc`). Kept out of the
    # repo because it pins a built store path; the build regenerates it each run.
    ./golden-skills.nix
  ];

  # The realized fleet-worker flake lives at /etc/fleet-worker so a launched copy resolves the
  # toolchain via `nix develop /etc/fleet-worker` with no fetch/build (closure realized at
  # build time). The golden-launch probe (SCENARIO-0065) resolves claude/lean-ctx/go/make and
  # the provider CLIs through this path. Source is wired by ./golden-skills.nix too.

  # Point claude-code at the baked skills discovery path.
  environment.sessionVariables.CLAUDE_SKILLS_DIR = "/etc/claude/skills";

  # FULL-golden marker (supersedes golden.nix's substrate marker) — proves a launched copy is
  # the realized FULL golden, not the substrate-only image, with no live build.
  environment.etc."fleet-golden-version".text =
    lib.mkForce "fleet-golden v2 FULL (STORY-0075/0077, ITER-0005c): realized toolchain + 13 curated skills\n";
}
