# fleet-worker/worker-container.nix
#
# Minimal NixOS configuration for a fleet WORKER running as an incus container.
# This is the declarative worker image (STORY-0075, flavor 1): stock NixOS + a
# non-root `worker` user + nix configured to SUBSTITUTE the agent tools from the
# numtide cache. The agent toolchain itself (claude-code, lean-ctx, go, …) is NOT
# baked in — the worker gets it at run time via `nix develop ./fleet-worker`
# (which substitutes prebuilt; see fleet-worker/flake.nix).
#
# Apply to a running stock `images:nixos/25.11` container by replacing
# /etc/nixos/configuration.nix and running `nixos-rebuild switch`. Keep the
# autogenerated ./incus.nix + lxc-container.nix imports the image ships with.
{ modulesPath, pkgs, ... }:

{
  imports = [
    "${modulesPath}/virtualisation/lxc-container.nix"
    ./incus.nix
  ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Non-root worker: claude-code refuses --dangerously-skip-permissions as root.
  users.users.worker = {
    isNormalUser = true;
    home = "/home/worker";
    extraGroups = [ "wheel" ];
  };
  security.sudo.wheelNeedsPassword = false;

  # Nix: flakes + the numtide binary cache SYSTEM-WIDE so the worker substitutes
  # claude-code / lean-ctx prebuilt (no build → no unprivileged-sandbox wall),
  # without needing per-command --accept-flake-config. worker is a trusted user so
  # the flake's own nixConfig substituters are honored too.
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    trusted-users = [ "root" "worker" ];
    extra-substituters = [ "https://cache.numtide.com" ];
    extra-trusted-public-keys = [ "niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=" ];
    # Unprivileged LXC has no kernel-namespace build sandbox; disable it
    # DECLARATIVELY so neither nixos-rebuild nor the worker's `nix develop` needs
    # --no-sandbox. Rely on substitution; the only builds are tiny (mkShell env,
    # activation scripts). (First bootstrap rebuild still needs NIX_CONFIG="sandbox
    # = false" since this isn't active yet; afterwards it's permanent.)
    sandbox = false;
  };
  nixpkgs.config.allowUnfree = true;

  # Declarative env defaults for ALL sessions (so a non-login `incus exec bash -c`
  # also has NIX_PATH — otherwise nixos-rebuild fails with "nixpkgs/nixos not found").
  environment.sessionVariables.NIX_PATH = "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix";

  environment.systemPackages = with pkgs; [ git bashInteractive ];

  system.stateVersion = "25.11";
}
