package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	paseto "aidanwoods.dev/go-paseto"
	"github.com/agent-sandbox/incus-dispatcher/grantauth"
)

func TestRunMint_GeneratesVerifiableGrant(t *testing.T) {
	// SCENARIO-0117: mint produces a grant that verifies against the issuer public key.
	tmpdir := t.TempDir()
	issuerKeyPath := filepath.Join(tmpdir, "issuer.key")

	// Generate a client key and write its public PEM.
	clientKey, err := grantauth.NewKey()
	if err != nil {
		t.Fatalf("NewKey: %v", err)
	}
	clientPubPEM, err := clientKey.PublicKeyPEM()
	if err != nil {
		t.Fatalf("clientKey.PublicKeyPEM: %v", err)
	}
	clientPubPath := filepath.Join(tmpdir, "client.pub")
	if err := os.WriteFile(clientPubPath, []byte(clientPubPEM), 0644); err != nil {
		t.Fatalf("WriteFile client pub: %v", err)
	}

	// Run mint; should create issuer key and emit a grant.
	var stdout bytes.Buffer
	args := []string{
		"--sub", "agent-host",
		"--aud", "laneq://agent-host:9999",
		"--ttl", "30m",
		"--client-pub", clientPubPath,
		"--issuer-key", issuerKeyPath,
		"--kid", "k1",
		"--client-kid", "c1",
		"--iss", "mac",
	}

	err = runMint(args, &stdout)
	if err != nil {
		t.Fatalf("runMint: %v", err)
	}

	grant := strings.TrimSpace(stdout.String())
	if grant == "" {
		t.Fatalf("runMint produced empty grant")
	}

	// Load the issuer key that was generated.
	issuerKey, err := grantauth.LoadEd25519PrivateKeyPEM(issuerKeyPath)
	if err != nil {
		t.Fatalf("LoadEd25519PrivateKeyPEM: %v", err)
	}

	// Parse and verify the grant against the issuer's public key.
	tok, err := paseto.NewParserWithoutExpiryCheck().ParseV4Public(issuerKey.PublicKey(), grant, nil)
	if err != nil {
		t.Fatalf("ParseV4Public: %v", err)
	}

	// Verify claims are correct.
	var sub, aud, iss, jti string
	if err := tok.Get("sub", &sub); err != nil || sub != "agent-host" {
		t.Errorf("sub: got %q, want agent-host (err %v)", sub, err)
	}
	if err := tok.Get("aud", &aud); err != nil || aud != "laneq://agent-host:9999" {
		t.Errorf("aud: got %q, want laneq://agent-host:9999 (err %v)", aud, err)
	}
	if err := tok.Get("iss", &iss); err != nil || iss != "mac" {
		t.Errorf("iss: got %q, want mac (err %v)", iss, err)
	}
	if err := tok.Get("jti", &jti); err != nil || jti == "" {
		t.Errorf("jti: got %q, want non-empty (err %v)", jti, err)
	}

	// Verify cnf binds the client public key.
	var cnf struct {
		Kid string `json:"kid"`
		Key string `json:"key"`
	}
	if err := tok.Get("cnf", &cnf); err != nil {
		t.Fatalf("cnf: %v", err)
	}
	if cnf.Kid != "c1" {
		t.Errorf("cnf.kid: got %q, want c1", cnf.Kid)
	}
	if cnf.Key != clientPubPEM {
		t.Errorf("cnf.key: does not match client public key PEM")
	}

	// Verify expiry is set correctly (TTL = 30m from now).
	var exp int64
	if err := tok.Get("exp", &exp); err != nil {
		t.Fatalf("exp: %v", err)
	}
	// Check that exp is approximately 30 minutes from now (within 5 seconds).
	now := time.Now().Unix()
	expectedExp := now + 30*60
	if exp < expectedExp-5 || exp > expectedExp+5 {
		t.Errorf("exp: got %d, expected ~%d (±5s)", exp, expectedExp)
	}
}

func TestRunMint_IssuerKeyAutoGeneratedOnFirstRun(t *testing.T) {
	// SCENARIO-0117: issuer key is auto-generated at default path on first mint;
	// second mint reuses the same key.
	tmpdir := t.TempDir()
	issuerKeyPath := filepath.Join(tmpdir, "issuer.key")
	clientPubPath := filepath.Join(tmpdir, "client.pub")

	clientKey, err := grantauth.NewKey()
	if err != nil {
		t.Fatalf("NewKey: %v", err)
	}
	clientPubPEM, err := clientKey.PublicKeyPEM()
	if err != nil {
		t.Fatalf("clientKey.PublicKeyPEM: %v", err)
	}
	if err := os.WriteFile(clientPubPath, []byte(clientPubPEM), 0644); err != nil {
		t.Fatalf("WriteFile client pub: %v", err)
	}

	// First mint: key should be created.
	var stdout1 bytes.Buffer
	args1 := []string{
		"--sub", "agent-host",
		"--aud", "laneq://agent-host:9999",
		"--ttl", "30m",
		"--client-pub", clientPubPath,
		"--issuer-key", issuerKeyPath,
		"--kid", "k1",
		"--client-kid", "c1",
		"--iss", "mac",
	}
	err = runMint(args1, &stdout1)
	if err != nil {
		t.Fatalf("runMint 1: %v", err)
	}

	// Verify the key file exists with mode 0600.
	stat, err := os.Stat(issuerKeyPath)
	if err != nil {
		t.Fatalf("Stat issuer key: %v", err)
	}
	if (stat.Mode() & os.ModePerm) != 0600 {
		t.Errorf("issuer key mode: got %o, want 0600", stat.Mode()&os.ModePerm)
	}

	grant1 := strings.TrimSpace(stdout1.String())

	// Parse grant1 and extract issuer public key.
	issuerKey1, err := grantauth.LoadEd25519PrivateKeyPEM(issuerKeyPath)
	if err != nil {
		t.Fatalf("LoadEd25519PrivateKeyPEM: %v", err)
	}
	pubKey1, err := issuerKey1.PublicKeyPEM()
	if err != nil {
		t.Fatalf("PublicKeyPEM 1: %v", err)
	}

	// Second mint: should reuse the same key.
	var stdout2 bytes.Buffer
	err = runMint(args1, &stdout2)
	if err != nil {
		t.Fatalf("runMint 2: %v", err)
	}

	issuerKey2, err := grantauth.LoadEd25519PrivateKeyPEM(issuerKeyPath)
	if err != nil {
		t.Fatalf("LoadEd25519PrivateKeyPEM 2: %v", err)
	}
	pubKey2, err := issuerKey2.PublicKeyPEM()
	if err != nil {
		t.Fatalf("PublicKeyPEM 2: %v", err)
	}

	// Public keys should be identical.
	if pubKey1 != pubKey2 {
		t.Errorf("issuer key changed between runs (not reused)")
	}

	// Both grants should verify against the issuer key.
	grant2 := strings.TrimSpace(stdout2.String())
	for i, grant := range []string{grant1, grant2} {
		_, err := paseto.NewParserWithoutExpiryCheck().ParseV4Public(issuerKey1.PublicKey(), grant, nil)
		if err != nil {
			t.Errorf("grant %d verification: %v", i+1, err)
		}
	}
}

func TestRunMint_ErrorOnMissingAudience(t *testing.T) {
	tmpdir := t.TempDir()
	clientPubPath := filepath.Join(tmpdir, "client.pub")
	clientKey, _ := grantauth.NewKey()
	clientPubPEM, _ := clientKey.PublicKeyPEM()
	os.WriteFile(clientPubPath, []byte(clientPubPEM), 0644)

	var stdout bytes.Buffer
	args := []string{
		"--sub", "agent-host",
		// Missing --aud
		"--ttl", "30m",
		"--client-pub", clientPubPath,
		"--kid", "k1",
		"--client-kid", "c1",
		"--iss", "mac",
	}

	err := runMint(args, &stdout)
	if err == nil {
		t.Fatalf("runMint: expected error on missing --aud, got nil")
	}
	if !strings.Contains(err.Error(), "aud") && !strings.Contains(err.Error(), "required") {
		t.Errorf("error should mention missing aud: %v", err)
	}
}

func TestRunMint_ErrorOnMissingClientPub(t *testing.T) {
	tmpdir := t.TempDir()
	issuerKeyPath := filepath.Join(tmpdir, "issuer.key")

	var stdout bytes.Buffer
	args := []string{
		"--sub", "agent-host",
		"--aud", "laneq://agent-host:9999",
		"--ttl", "30m",
		// Missing --client-pub
		"--issuer-key", issuerKeyPath,
		"--kid", "k1",
		"--client-kid", "c1",
		"--iss", "mac",
	}

	err := runMint(args, &stdout)
	if err == nil {
		t.Fatalf("runMint: expected error on missing --client-pub, got nil")
	}
	if !strings.Contains(err.Error(), "client-pub") && !strings.Contains(err.Error(), "required") {
		t.Errorf("error should mention missing client-pub: %v", err)
	}
}

func TestRunMint_ErrorOnBadTTL(t *testing.T) {
	tmpdir := t.TempDir()
	clientPubPath := filepath.Join(tmpdir, "client.pub")
	issuerKeyPath := filepath.Join(tmpdir, "issuer.key")

	clientKey, _ := grantauth.NewKey()
	clientPubPEM, _ := clientKey.PublicKeyPEM()
	os.WriteFile(clientPubPath, []byte(clientPubPEM), 0644)

	var stdout bytes.Buffer
	args := []string{
		"--sub", "agent-host",
		"--aud", "laneq://agent-host:9999",
		"--ttl", "not-a-duration", // Invalid TTL
		"--client-pub", clientPubPath,
		"--issuer-key", issuerKeyPath,
		"--kid", "k1",
		"--client-kid", "c1",
		"--iss", "mac",
	}

	err := runMint(args, &stdout)
	if err == nil {
		t.Fatalf("runMint: expected error on bad ttl, got nil")
	}
	if !strings.Contains(err.Error(), "ttl") && !strings.Contains(err.Error(), "duration") {
		t.Errorf("error should mention ttl parsing: %v", err)
	}
}

func TestRunKeygen_GeneratesAndSavesKeys(t *testing.T) {
	tmpdir := t.TempDir()
	privPath := filepath.Join(tmpdir, "priv.pem")
	pubPath := filepath.Join(tmpdir, "pub.pem")

	var stdout bytes.Buffer
	args := []string{
		"--out-priv", privPath,
		"--out-pub", pubPath,
	}

	err := runKeygen(args, &stdout)
	if err != nil {
		t.Fatalf("runKeygen: %v", err)
	}

	// Verify private key file exists with mode 0600.
	privStat, err := os.Stat(privPath)
	if err != nil {
		t.Fatalf("Stat priv key: %v", err)
	}
	if (privStat.Mode() & os.ModePerm) != 0600 {
		t.Errorf("priv key mode: got %o, want 0600", privStat.Mode()&os.ModePerm)
	}

	// Verify public key file exists with mode 0644.
	pubStat, err := os.Stat(pubPath)
	if err != nil {
		t.Fatalf("Stat pub key: %v", err)
	}
	if (pubStat.Mode() & os.ModePerm) != 0644 {
		t.Errorf("pub key mode: got %o, want 0644", pubStat.Mode()&os.ModePerm)
	}

	// Verify private key can be loaded and round-trips.
	key, err := grantauth.LoadEd25519PrivateKeyPEM(privPath)
	if err != nil {
		t.Fatalf("LoadEd25519PrivateKeyPEM: %v", err)
	}

	// Verify public key is PKIX-parseable.
	pubData, err := os.ReadFile(pubPath)
	if err != nil {
		t.Fatalf("ReadFile pub key: %v", err)
	}
	if !strings.Contains(string(pubData), "-----BEGIN PUBLIC KEY-----") {
		t.Errorf("public key file not in PKIX PEM format")
	}

	// Verify the loaded key's public key matches the saved one.
	expectedPub, err := key.PublicKeyPEM()
	if err != nil {
		t.Fatalf("PublicKeyPEM: %v", err)
	}
	if string(pubData) != expectedPub {
		t.Errorf("saved public key does not match derived public key")
	}
}

func TestRunKeygen_RefusesToClobberExistingPrivateKey(t *testing.T) {
	tmpdir := t.TempDir()
	privPath := filepath.Join(tmpdir, "priv.pem")
	pubPath := filepath.Join(tmpdir, "pub.pem")

	// Create first key.
	var stdout bytes.Buffer
	args := []string{
		"--out-priv", privPath,
		"--out-pub", pubPath,
	}
	err := runKeygen(args, &stdout)
	if err != nil {
		t.Fatalf("runKeygen 1: %v", err)
	}

	// Try to create another key without --force; should fail.
	var stdout2 bytes.Buffer
	err = runKeygen(args, &stdout2)
	if err == nil {
		t.Fatalf("runKeygen 2: expected error when --out-priv exists, got nil")
	}
	if !strings.Contains(err.Error(), "already exists") && !strings.Contains(err.Error(), "clobber") && !strings.Contains(err.Error(), "force") {
		t.Errorf("error should mention existing file or --force: %v", err)
	}

	// Try with --force; should succeed.
	var stdout3 bytes.Buffer
	args3 := []string{
		"--out-priv", privPath,
		"--out-pub", pubPath,
		"--force",
	}
	err = runKeygen(args3, &stdout3)
	if err != nil {
		t.Fatalf("runKeygen 3 (with --force): %v", err)
	}
}

func TestRunMint_KidInFooter(t *testing.T) {
	// AC-3: footer kid must match --kid flag.
	tmpdir := t.TempDir()
	issuerKeyPath := filepath.Join(tmpdir, "issuer.key")
	clientPubPath := filepath.Join(tmpdir, "client.pub")

	clientKey, _ := grantauth.NewKey()
	clientPubPEM, _ := clientKey.PublicKeyPEM()
	os.WriteFile(clientPubPath, []byte(clientPubPEM), 0644)

	var stdout bytes.Buffer
	args := []string{
		"--sub", "agent-host",
		"--aud", "laneq://agent-host:9999",
		"--ttl", "30m",
		"--client-pub", clientPubPath,
		"--issuer-key", issuerKeyPath,
		"--kid", "k2", // Set kid to k2
		"--client-kid", "c1",
		"--iss", "mac",
	}

	err := runMint(args, &stdout)
	if err != nil {
		t.Fatalf("runMint: %v", err)
	}

	grant := strings.TrimSpace(stdout.String())
	issuerKey, _ := grantauth.LoadEd25519PrivateKeyPEM(issuerKeyPath)
	tok, err := paseto.NewParserWithoutExpiryCheck().ParseV4Public(issuerKey.PublicKey(), grant, nil)
	if err != nil {
		t.Fatalf("ParseV4Public: %v", err)
	}

	// Check the footer for kid.
	footer := tok.Footer()
	var footerMap map[string]string
	if err := json.Unmarshal(footer, &footerMap); err != nil {
		t.Fatalf("unmarshal footer: %v", err)
	}
	if footerMap["kid"] != "k2" {
		t.Errorf("footer kid: got %q, want k2", footerMap["kid"])
	}
}

func TestRunMint_WritesToOutFile(t *testing.T) {
	tmpdir := t.TempDir()
	issuerKeyPath := filepath.Join(tmpdir, "issuer.key")
	clientPubPath := filepath.Join(tmpdir, "client.pub")
	outPath := filepath.Join(tmpdir, "grant.txt")

	clientKey, _ := grantauth.NewKey()
	clientPubPEM, _ := clientKey.PublicKeyPEM()
	os.WriteFile(clientPubPath, []byte(clientPubPEM), 0644)

	var stdout bytes.Buffer
	args := []string{
		"--sub", "agent-host",
		"--aud", "laneq://agent-host:9999",
		"--ttl", "30m",
		"--client-pub", clientPubPath,
		"--issuer-key", issuerKeyPath,
		"--kid", "k1",
		"--client-kid", "c1",
		"--iss", "mac",
		"--out", outPath,
	}

	err := runMint(args, &stdout)
	if err != nil {
		t.Fatalf("runMint: %v", err)
	}

	// Verify grant was written to the file.
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	grant := strings.TrimSpace(string(data))
	if grant == "" {
		t.Fatalf("grant file is empty")
	}

	// Verify file permissions (0600).
	stat, err := os.Stat(outPath)
	if err != nil {
		t.Fatalf("Stat out file: %v", err)
	}
	if (stat.Mode() & os.ModePerm) != 0600 {
		t.Errorf("out file mode: got %o, want 0600", stat.Mode()&os.ModePerm)
	}

	// Verify the grant is valid.
	issuerKey, _ := grantauth.LoadEd25519PrivateKeyPEM(issuerKeyPath)
	_, err = paseto.NewParserWithoutExpiryCheck().ParseV4Public(issuerKey.PublicKey(), grant, nil)
	if err != nil {
		t.Fatalf("grant verification: %v", err)
	}

	// Verify stdout is empty (grant was only written to file).
	if stdout.Len() > 0 {
		t.Errorf("stdout should be empty when using --out, got: %s", stdout.String())
	}
}

// TestRunMint_ConcurrentSafeIssuerKeyCreation verifies that concurrent mints
// share one issuer key and never clobber it.
func TestRunMint_ConcurrentSafeIssuerKeyCreation(t *testing.T) {
	tmpdir := t.TempDir()
	issuerKeyPath := filepath.Join(tmpdir, "issuer.key")
	clientPubPath := filepath.Join(tmpdir, "client.pub")

	clientKey, _ := grantauth.NewKey()
	clientPubPEM, _ := clientKey.PublicKeyPEM()
	os.WriteFile(clientPubPath, []byte(clientPubPEM), 0644)

	args := []string{
		"--sub", "agent-host",
		"--aud", "laneq://agent-host:9999",
		"--ttl", "30m",
		"--client-pub", clientPubPath,
		"--issuer-key", issuerKeyPath,
		"--kid", "k1",
		"--client-kid", "c1",
		"--iss", "mac",
	}

	// First mint creates the issuer key.
	var stdout1 bytes.Buffer
	err := runMint(args, &stdout1)
	if err != nil {
		t.Fatalf("runMint 1: %v", err)
	}
	grant1 := strings.TrimSpace(stdout1.String())

	// Load the issuer key and its public key.
	issuerKey1, err := grantauth.LoadEd25519PrivateKeyPEM(issuerKeyPath)
	if err != nil {
		t.Fatalf("LoadEd25519PrivateKeyPEM 1: %v", err)
	}
	pubKey1, err := issuerKey1.PublicKeyPEM()
	if err != nil {
		t.Fatalf("PublicKeyPEM 1: %v", err)
	}

	// Second mint should reuse the same issuer key.
	var stdout2 bytes.Buffer
	err = runMint(args, &stdout2)
	if err != nil {
		t.Fatalf("runMint 2: %v", err)
	}
	grant2 := strings.TrimSpace(stdout2.String())

	// Load the issuer key again.
	issuerKey2, err := grantauth.LoadEd25519PrivateKeyPEM(issuerKeyPath)
	if err != nil {
		t.Fatalf("LoadEd25519PrivateKeyPEM 2: %v", err)
	}
	pubKey2, err := issuerKey2.PublicKeyPEM()
	if err != nil {
		t.Fatalf("PublicKeyPEM 2: %v", err)
	}

	// Public keys MUST be identical (issuer key was reused, not regenerated).
	if pubKey1 != pubKey2 {
		t.Errorf("issuer key changed between mints (SECURITY: trust root was clobbered)")
	}

	// Both grants MUST verify against the issuer's public key.
	for i, grant := range []string{grant1, grant2} {
		_, err := paseto.NewParserWithoutExpiryCheck().ParseV4Public(issuerKey1.PublicKey(), grant, nil)
		if err != nil {
			t.Errorf("grant %d verification: %v", i+1, err)
		}
	}
}

// TestRunKeygen_AtomicClobberProtection verifies that O_EXCL prevents clobbering.
func TestRunKeygen_AtomicClobberProtection(t *testing.T) {
	tmpdir := t.TempDir()
	privPath := filepath.Join(tmpdir, "priv.pem")
	pubPath := filepath.Join(tmpdir, "pub.pem")

	// First keygen creates the key.
	var stdout bytes.Buffer
	args := []string{
		"--out-priv", privPath,
		"--out-pub", pubPath,
	}
	err := runKeygen(args, &stdout)
	if err != nil {
		t.Fatalf("runKeygen 1: %v", err)
	}

	// Read the original private key bytes.
	origPrivData, err := os.ReadFile(privPath)
	if err != nil {
		t.Fatalf("ReadFile original priv: %v", err)
	}

	// Try to keygen again without --force; should fail.
	var stdout2 bytes.Buffer
	err = runKeygen(args, &stdout2)
	if err == nil {
		t.Fatalf("runKeygen 2: expected error on existing file, got nil")
	}

	// Verify the original private key bytes are UNCHANGED.
	unchangedPrivData, err := os.ReadFile(privPath)
	if err != nil {
		t.Fatalf("ReadFile unchanged priv: %v", err)
	}
	if string(origPrivData) != string(unchangedPrivData) {
		t.Errorf("private key file was clobbered despite clobber protection")
	}
}

// TestRunMint_ConcurrentMintsSameKey simulates goroutine-based concurrent mints
// (sequential execution for contract testing under -race).
func TestRunMint_ConcurrentMintsSameKey(t *testing.T) {
	tmpdir := t.TempDir()
	issuerKeyPath := filepath.Join(tmpdir, "issuer.key")
	clientPubPath := filepath.Join(tmpdir, "client.pub")

	clientKey, _ := grantauth.NewKey()
	clientPubPEM, _ := clientKey.PublicKeyPEM()
	os.WriteFile(clientPubPath, []byte(clientPubPEM), 0644)

	baseArgs := []string{
		"--sub", "agent-host",
		"--aud", "laneq://agent-host:9999",
		"--ttl", "30m",
		"--client-pub", clientPubPath,
		"--issuer-key", issuerKeyPath,
		"--kid", "k1",
		"--client-kid", "c1",
		"--iss", "mac",
	}

	const numGoroutines = 5
	var wg sync.WaitGroup
	results := make([]string, numGoroutines)
	errors := make([]error, numGoroutines)

	// Launch multiple mints concurrently.
	for i := 0; i < numGoroutines; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			var stdout bytes.Buffer
			err := runMint(baseArgs, &stdout)
			if err != nil {
				errors[idx] = err
				return
			}
			results[idx] = strings.TrimSpace(stdout.String())
		}(i)
	}
	wg.Wait()

	// All mints must succeed.
	for i := 0; i < numGoroutines; i++ {
		if errors[i] != nil {
			t.Errorf("mint %d: %v", i, errors[i])
		}
	}

	// Load the issuer key (should exist and be consistent).
	issuerKey, err := grantauth.LoadEd25519PrivateKeyPEM(issuerKeyPath)
	if err != nil {
		t.Fatalf("LoadEd25519PrivateKeyPEM: %v", err)
	}

	// All grants must verify against the same issuer public key.
	for i := 0; i < numGoroutines; i++ {
		grant := results[i]
		if grant == "" {
			t.Errorf("mint %d produced empty grant", i)
			continue
		}
		_, err := paseto.NewParserWithoutExpiryCheck().ParseV4Public(issuerKey.PublicKey(), grant, nil)
		if err != nil {
			t.Errorf("mint %d grant verification: %v", i, err)
		}
	}
}
