package main

import (
	"crypto/sha256"
	"fmt"
	"time"
)

// GenomeSource enumerates the origin of a genome entry (STORY-0032 AC-1).
type GenomeSource string

const (
	GenomeSourceBootstrap GenomeSource = "bootstrap"  // Initial, hardcoded configuration
	GenomeSourceLearned   GenomeSource = "learned"    // Detector-generated candidate
	GenomeSourcePromoted  GenomeSource = "promoted"   // Learned entry promoted to active
	GenomeSourceExperiment GenomeSource = "experiment" // Trial-run mutation
)

// GenomeStatus enumerates the lifecycle state of a genome entry (STORY-0032 AC-1).
type GenomeStatus string

const (
	GenomeStatusActive    GenomeStatus = "active"     // Current active genome in production
	GenomeStatusCandidate GenomeStatus = "candidate"  // Proposed mutation, awaiting trial
	GenomeStatusRejected  GenomeStatus = "rejected"   // Trial did not improve; proposal discarded
	GenomeStatusReverted  GenomeStatus = "reverted"   // Promoted mutation later regressed; prior restored
)

// MutationTarget enumerates the exact six mutation targets (STORY-0032 AC-2).
// Protected invariants (secret_handling, lease_safety, audit_requirements, hard_budget_guardrails,
// kernel_safety) are excluded and guarded at proposal construction (AC-3).
type MutationTarget string

const (
	MutationTargetPromptTweak              MutationTarget = "prompt_tweak"
	MutationTargetRoutingHeuristic         MutationTarget = "routing_heuristic"
	MutationTargetProviderModelHeuristic   MutationTarget = "provider_model_heuristic"
	MutationTargetBudgetEscalation         MutationTarget = "budget_escalation"
	MutationTargetExecutionPolicy          MutationTarget = "execution_policy"
	MutationTargetThreadHandoffTemplate    MutationTarget = "thread_handoff_template"
)

// IsValidMutationTarget reports whether t is a valid (mutable) mutation target.
func IsValidMutationTarget(t MutationTarget) bool {
	switch t {
	case MutationTargetPromptTweak,
		MutationTargetRoutingHeuristic,
		MutationTargetProviderModelHeuristic,
		MutationTargetBudgetEscalation,
		MutationTargetExecutionPolicy,
		MutationTargetThreadHandoffTemplate:
		return true
	}
	return false
}

// ProtectedTargets lists the invariants that must never be mutated by the genome engine (STORY-0032 AC-3).
var ProtectedTargets = map[string]bool{
	"secret_handling":       true,
	"lease_safety":          true,
	"audit_requirements":    true,
	"hard_budget_guardrails": true,
	"kernel_safety":         true,
}

// GenomeEntry represents one immutable genome state: a prompt, heuristic, policy, or template
// that is actively used in dispatch or a candidate awaiting trial (STORY-0032 AC-1).
type GenomeEntry struct {
	Version      int            `json:"version"`       // Monotonically increasing version; used for revert
	ContentHash  string         `json:"content_hash"`  // SHA256 of the entry content for integrity
	Source       GenomeSource   `json:"source"`        // bootstrap, learned, promoted, or experiment
	Status       GenomeStatus   `json:"status"`        // active, candidate, rejected, or reverted
	Target       MutationTarget `json:"target"`        // what is being mutated
	Domain       string         `json:"domain"`        // worker_kind the entry applies to
	Content      string         `json:"content"`       // the actual prompt/heuristic/template text
	PriorVersion int            `json:"prior_version,omitempty"` // For revert: points to the version to restore
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// ContentSHA256 computes the SHA256 hash of the entry content.
func ContentSHA256(content string) string {
	h := sha256.Sum256([]byte(content))
	return fmt.Sprintf("%x", h)
}

// MutationProposal is a candidate genome entry generated by the pattern detector,
// awaiting trial and promotion (STORY-0032 AC-4 design note §4).
type MutationProposal struct {
	ID          string           `json:"id"`           // Unique proposal ID (e.g., "mut-001")
	Domain      string           `json:"domain"`       // worker_kind the mutation targets
	Target      MutationTarget   `json:"target"`       // What is being mutated (must be valid, non-protected)
	Source      GenomeSource     `json:"source"`       // "learned" for detector-generated
	Status      GenomeStatus     `json:"status"`       // "candidate" at creation
	Version     int              `json:"version"`      // Genome version this proposal would supersede
	ContentHash string           `json:"content_hash"` // SHA256 of proposed content
	Content     string           `json:"content"`      // The proposed prompt/heuristic/template
	Rationale   string           `json:"rationale"`    // Human-readable: which pattern triggered it
	EvidenceRefs []string        `json:"evidence_refs"` // Prior run IDs from the firing pattern (AC-4 trail)
	ProposedAt  time.Time        `json:"proposed_at"`
	TrialRunID  string           `json:"trial_run_id,omitempty"` // Set when trial begins
	PriorVersion int             `json:"prior_version,omitempty"` // For revert: prior active version
}

// NewMutationProposal creates a new MutationProposal with protected-invariant guard (AC-3).
// It returns an error if the target is protected or invalid.
// The proposal is NOT appended to audit here; the caller decides when to call Propose() for audit.
func NewMutationProposal(
	id, domain string,
	target MutationTarget,
	content, rationale string,
	evidenceRefs []string,
	audioLog AuditLog,
) (*MutationProposal, error) {
	// Guard against protected targets (AC-3).
	if ProtectedTargets[string(target)] {
		// Record rejection in audit.
		audioLog.Append(AuditEntry{
			Actor:  "genome_engine",
			Kind:   AuditKindMutation,
			Detail: fmt.Sprintf("rejected: protected-invariant target=%q", target),
		})
		return nil, fmt.Errorf("mutation target %q is protected from automatic mutation", target)
	}

	// Guard against invalid targets (AC-2).
	if !IsValidMutationTarget(target) {
		audioLog.Append(AuditEntry{
			Actor:  "genome_engine",
			Kind:   AuditKindMutation,
			Detail: fmt.Sprintf("rejected: invalid target=%q", target),
		})
		return nil, fmt.Errorf("mutation target %q is not valid", target)
	}

	mp := &MutationProposal{
		ID:           id,
		Domain:       domain,
		Target:       target,
		Source:       GenomeSourceLearned,
		Status:       GenomeStatusCandidate,
		ContentHash:  ContentSHA256(content),
		Content:      content,
		Rationale:    rationale,
		EvidenceRefs: make([]string, len(evidenceRefs)),
		ProposedAt:   time.Now(),
	}
	copy(mp.EvidenceRefs, evidenceRefs)
	return mp, nil
}

// Propose records the proposal in the audit log with status=candidate (AC-4).
func (mp *MutationProposal) Propose(audioLog AuditLog) error {
	_, err := audioLog.Append(AuditEntry{
		Actor:  "genome_engine",
		Kind:   AuditKindMutation,
		Detail: fmt.Sprintf("propose id=%s target=%s status=candidate rationale=%q", mp.ID, mp.Target, mp.Rationale),
	})
	return err
}

// Promote transitions the proposal to status=active, source=promoted, assigning a new version
// and retaining the prior version for revert capability (AC-4).
// Enforces two critical guards: (1) re-check protected targets (AC-3 dual enforcement),
// (2) validate the proposal is in candidate status (AC-4 state machine).
func (mp *MutationProposal) Promote(version int, priorVersion int, audioLog AuditLog) (*GenomeEntry, error) {
	// Guard 1: Validate incoming status is candidate (AC-4 state machine protection).
	if mp.Status != GenomeStatusCandidate {
		audioLog.Append(AuditEntry{
			Actor:  "genome_engine",
			Kind:   AuditKindMutation,
			Detail: fmt.Sprintf("rejected: invalid state for promotion id=%s from_status=%s", mp.ID, mp.Status),
		})
		return nil, fmt.Errorf("cannot promote from status %q; only candidate proposals may be promoted", mp.Status)
	}

	// Guard 2: Re-check protected targets (AC-3 dual enforcement: construction AND promotion).
	if ProtectedTargets[string(mp.Target)] {
		audioLog.Append(AuditEntry{
			Actor:  "genome_engine",
			Kind:   AuditKindMutation,
			Detail: fmt.Sprintf("rejected: protected-invariant at promotion id=%s target=%q", mp.ID, mp.Target),
		})
		return nil, fmt.Errorf("mutation target %q is protected from automatic mutation; cannot promote", mp.Target)
	}

	mp.PriorVersion = priorVersion

	entry := &GenomeEntry{
		Version:      version,
		ContentHash:  mp.ContentHash,
		Source:       GenomeSourcePromoted,
		Status:       GenomeStatusActive,
		Target:       mp.Target,
		Domain:       mp.Domain,
		Content:      mp.Content,
		PriorVersion: priorVersion,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	_, err := audioLog.Append(AuditEntry{
		Actor:  "genome_engine",
		Kind:   AuditKindMutation,
		Detail: fmt.Sprintf("promote id=%s status=active version=%d prior_version=%d", mp.ID, version, priorVersion),
	})
	if err != nil {
		return nil, err
	}

	return entry, nil
}

// Keep keeps the proposal as a candidate for another trial (AC-4).
// Only acts on candidate proposals (AC-4 state machine protection).
func (mp *MutationProposal) Keep(audioLog AuditLog) error {
	// Guard: Only candidate proposals can be kept.
	if mp.Status != GenomeStatusCandidate {
		audioLog.Append(AuditEntry{
			Actor:  "genome_engine",
			Kind:   AuditKindMutation,
			Detail: fmt.Sprintf("rejected: invalid state for keep id=%s from_status=%s", mp.ID, mp.Status),
		})
		return fmt.Errorf("cannot keep proposal from status %q; only candidate proposals may be kept", mp.Status)
	}

	_, err := audioLog.Append(AuditEntry{
		Actor:  "genome_engine",
		Kind:   AuditKindMutation,
		Detail: fmt.Sprintf("keep id=%s status=candidate (inconclusive, retry trial)", mp.ID),
	})
	return err
}

// Reject marks the proposal as rejected; the proposal key is freed for future detection (AC-4).
// Only acts on candidate proposals (AC-4 state machine protection).
func (mp *MutationProposal) Reject(audioLog AuditLog) error {
	// Guard: Only candidate proposals can be rejected.
	if mp.Status != GenomeStatusCandidate {
		audioLog.Append(AuditEntry{
			Actor:  "genome_engine",
			Kind:   AuditKindMutation,
			Detail: fmt.Sprintf("rejected: invalid state for reject id=%s from_status=%s", mp.ID, mp.Status),
		})
		return fmt.Errorf("cannot reject proposal from status %q; only candidate proposals may be rejected", mp.Status)
	}

	mp.Status = GenomeStatusRejected
	_, err := audioLog.Append(AuditEntry{
		Actor:  "genome_engine",
		Kind:   AuditKindMutation,
		Detail: fmt.Sprintf("reject id=%s status=rejected (trial did not improve)", mp.ID),
	})
	return err
}

// Revert restores a prior active version, marking the mutation as reverted (AC-4).
// Restores the prior entry's content, version, AND source (preserves provenance).
func (mp *MutationProposal) Revert(priorEntry *GenomeEntry, audioLog AuditLog) (*GenomeEntry, error) {
	if priorEntry == nil {
		return nil, fmt.Errorf("cannot revert without a prior entry")
	}

	// Create a new entry that restores the prior content, version, and source.
	// The source is from the prior entry (e.g., bootstrap, learned, promoted).
	newEntry := &GenomeEntry{
		Version:      priorEntry.Version + 1,
		ContentHash:  priorEntry.ContentHash,
		Source:       priorEntry.Source, // Restore the prior entry's source (not mislabel as promoted)
		Status:       GenomeStatusReverted,
		Target:       priorEntry.Target,
		Domain:       priorEntry.Domain,
		Content:      priorEntry.Content, // Genuinely restore prior content
		PriorVersion: priorEntry.Version,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	_, err := audioLog.Append(AuditEntry{
		Actor:  "genome_engine",
		Kind:   AuditKindMutation,
		Detail: fmt.Sprintf("revert id=%s status=reverted restored_version=%d", mp.ID, priorEntry.Version),
	})
	if err != nil {
		return nil, err
	}

	return newEntry, nil
}

// SetTrialRunID wires the trial run ID onto the proposal, linking the experiment to this proposal.
// Called when a trial begins to establish the audit trail (AC-4 evidence trail).
func (mp *MutationProposal) SetTrialRunID(runID string) {
	mp.TrialRunID = runID
}
